### ISSUE TITLE
Windows requires package source?

### ISSUE THREAD

**Issue by salderma** [example42/puppet-puppet#105]
Hi,
It looks like some attempt has been made to make this module work on windows.  I'm not sure when the last time anyone looked at it was, but it seems like puppet now requires the package source attribute when managing packages on Windows with it's default provider.  This module doesn't have code to override package source within the package resource definition -

https://github.com/example42/puppet-puppet/blob/master/manifests/init.pp#L721

Even if it did, it does not seem very reasonable since there is no good way to set a default parameter value to the install executable.  I see two possible resultions...

1.  Setup to use Chocolatey, which I'm not familiar with, but seems to be a really nice yum/apt like package repo system for Windows and is a valid puppet package provider.

2.  Setup logic using a $puppet::manage_package boolean to avoid defining the package resource on Windows platforms.  I took a similar approach patching your SSH module for Solaris since it has similar reqiurements.

What are your thoughts?

**Comment by alvagante** [comment]
Honestly I'm not using Puppet on Windows and have not much experience on it, I think that Chocolatey is the choice of reference when managing packages on Windows, so I would take it for granted and present when trying to support Windows on the modules.

**Comment by salderma** [comment]
Ok.  I'll work on a patch.  I may also follow up with patches for the monitoring integration.

**Comment by salderma** [comment]
So as a followup on this, it does seem that when we have example42/puppi, example42/puppet-monitor, and example42/puppet-puppet installed with the latest versions, things work well on Windows.  The one issue I did encounter was what seems to me to be a logic problem in example42/puppet-puppet/manifests/init.pp:854:

    ### Service monitoring, if enabled ( monitor => true )
    if $puppet::monitor_tool and $puppet::runmode == 'service' {

I would think this ought to test **$puppet::monitor** instead of (or in addition to) **$puppet::monitor_tool**, what do you think?  The case I ran into is when $puppet::monitor is false, but the node inherits $puppet::monitor_tool from the global $::monitor_tool.  This causes a windows machine to want to install example42/puppet-nrpe when $::monitor_tool = 'nagios'.

I'm going to continue to investigate extending the monitor subsystem (at least for nagios/icinga) to help windows use the NSCA client instead of NRPE, but I've got a long way to go on that.

**Comment by alvagante** [comment]
Yes, you are right, ty

**Comment by salderma** [comment]
Thanks, I'll close this issue, my initial hurdles have all been conquered!
